server:
  port: 8010
spring:
  application:
    name: biz-service
  datasource:
    url: jdbc:mysql://47.104.94.106:3307/alibaba-order?useSSL=false
    username: root
    password: rbjf_DEV123
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    alibaba:
      seata:
        tx-service-group: